### ISSUE TITLE
how to make LWIP work?

### ISSUE THREAD

**Issue by gqqh** [cnplab/mini-os#17]
I has built minios with LWIP1.3.2, and config vif = ['ip=10.10.1.3'],but cannot ping the ip through, and I wrote a daytime client to get message from the daytime server at TCP port 13,nothing to respond.

**Comment by skuenzer** [comment]
How do you compile your Mini-OS image? Did you write a new application together with Mini-OS?

**Comment by gqqh** [comment]
I set XEN_ROOT=xen-4.4.1, and I download and unzip lwip-1.3.2.zip under minios/ . And then make LWIPDIR=lwip-1.3.2 , but this time I even cannot compile success. 
I hadn't write a new application together with Mini-OS, and just use the daytime server application.

**Comment by skuenzer** [comment]
We recently updated lwIP to a more recent version (> 1.4.1). However, you do not need to download lwIP by your own because it gets automatically downloaded and prepared for Mini-OS when you build our latest toolchain. Please checkout the latest version, call `make distclean` and `make` again. Be sure that you also have our latest version of Mini-OS (because it includes an updated lwIP driver).
After that, it might be that the daytime server application cannot be compiled out-of-the box. In this case you would just need to update the daytime server application code to work with the updated lwIP API (sorry, we didn't do this yet; we are happy to receive a commit ;-) ).
When you build your image, please also set `LWIP_ROOT=[path-to-toolchain]/x86_64-root/x86_64-xen-elf`, `CONFIG_LWIP_CHECKSUM_NOGEN=n` and `CONFIG_LWIP_CHECKSUM_NOCHECK=y`.
These settings ensure proper handling of checksums with the new netmap based netfront.
Please be sure that your also attach your vif to a VALE bridge in your guest domain config.

**Comment by jinxuan** [comment]
Hi,
My goal is to compile a minios (not click os) with LwIP support.

I use use the toolchain to download the latest LwIP. I'm trying to compile minios with lwIP but still not succeed.  I have set these three environment variables you specified.

I explicitly change "CONFIG_LWIP ?= $(lwip)" to y in the makefile. And I got an error as follows:

```
find: `/src': No such file or directory
[ -e include/xen ] || ln -sf /home/jinxuanw/xen-4.4.1/xen/include/public include/xen
[ -e include/mini-os ] || ln -sf . include/mini-os
[ -e include/x86/mini-os ] || ln -sf . include/x86/mini-os
gcc -DCONFIG_START_NETWORK -DCONFIG_SPARSE_BSS -DCONFIG_BLKFRONT -DCONFIG_NETFRONT -DCONFIG_KBDFRONT -DCONFIG_FBFRONT -DCONFIG_CONSFRONT -DCONFIG_XENBUS -fno-builtin -Wall -Werror -Wredundant-decls -Wno-format -Wno-redundant-decls -fno-stack-protector -fgnu89-inline -Wstrict-prototypes -Wnested-externs -Wpointer-arith -Winline -g -DCONFIG_PVH -D__INSIDE_MINIOS__ -m64 -mno-red-zone -fno-reorder-blocks -fno-asynchronous-unwind-tables -isystem /home/jinxuanw/mini-os/include -D__MINIOS__ -D__XEN_INTERFACE_VERSION__=0x00030205  -isystem /home/jinxuanw/mini-os/include/x86 -isystem /home/jinxuanw/mini-os/include/x86/x86_64 -c lwip-net.c -o /home/jinxuanw/mini-os/lwip-net.o
lwip-net.c: In function ‘netfrontif_init’:
lwip-net.c:353:5: error: implicit declaration of function ‘printf’ [-Werror=implicit-function-declaration]
     LWIP_ASSERT("netif != NULL", (netif != NULL));
     ^
lwip-net.c:353:5: error: implicit declaration of function ‘fflush’ [-Werror=implicit-function-declaration]
In file included from /usr/local/include/lwip/arch.h:43:0,
                 from /usr/local/include/lwip/debug.h:35,
                 from /usr/local/include/lwip/opt.h:46,
                 from /home/jinxuanw/mini-os/include/lwip-net.h:43,
                 from lwip-net.c:83:
lwip-net.c:353:5: error: ‘stdout’ undeclared (first use in this function)
     LWIP_ASSERT("netif != NULL", (netif != NULL));
     ^
lwip-net.c:353:5: note: each undeclared identifier is reported only once for each function it appears in
lwip-net.c:411:2: error: implicit declaration of function ‘netfront_get_hwaddr’ [-Werror=implicit-function-declaration]
  if (!netfront_get_hwaddr(nfi->dev, &nfi->hwaddr)) {
  ^
lwip-net.c:411:2: error: nested extern declaration of ‘netfront_get_hwaddr’ [-Werror=nested-externs]
lwip-net.c:436:5: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
     NETIF_INIT_SNMP(netif, snmp_ifType_ethernet_csmacd, NETFRONTIF_SPEED);
     ^
cc1: all warnings being treated as errors
make: *** [/home/jinxuanw/mini-os/lwip-net.o] Error 1
```

One thing I notice is that environment variable $LWIP_ROOT is not used by the Makefile(Which use the $lwIP dir environment variable). But $LWIP_ROOT is used int stub.mk. But I'm also not able to use that stub.mk to generate a image either.

My question is as follows:

"What is that stub.mk used for?"
"How to correctly generate a minios image with LwIP support so that I can use LwIP socket?"

**Comment by fmanco** [comment]
Hi

`minios/stub.mk` is the makefile we use to compile external applications with our version of MiniOS. `minios/Makefile` is the upstream version that we don't use and is going to be clean at some point in time.

Follows a minimal makefile you can use to build external applications on top of MiniOS using our `stub.mk`, and including LwIP. Basically the application would be a single `main.c` file.

```
STUB_APP_OBJS0 := main.o
include $(MINIOS_ROOT)/stub.mk
```

Let me know if you have more questions!

**Comment by stevepp** [comment]
Hi, is this problem resolved? I tried to build a trivial helloworld c app following fmanco's suggestion. But it failed with an error "No rule to make target ". Looks like it is not so obvious to build external applications on mini-os. Could you please give more details?

One more question is: is it possible to port some existing applications, such as a http server, to run atop Mini-OS?

**Comment by fmanco** [comment]
Hi

You need to be more specific than "No rule to make target". Maybe you can put here the output of the build.

Porting an application to MiniOS is not trivial, the APIs are completely different from Linux and POSIX support is far from being complete. Therefore porting an application requires rewriting parts of the code (network, disk access, etc).

**Comment by fmanco** [comment]
Hi. Do you have any updates? Should I close this?

Thanks

**Comment by stevepp** [comment]
Yes, please close it.
